name: Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup OCaml
      uses: avsm/setup-ocaml@v2
    - name: Pin locally
      run: opam pin -y add -n .
    - name: Build and test
      run: opam install -y -t odoc js_of_ocaml js_of_ocaml-ppx alg
    - name: Build doc
      run: eval $(opam env) && make -C docs
    - name: Deploy doc
      uses: JamesIves/github-pages-deploy-action@4.1.6
      with:
        branch: gh-pages
        folder: docs